submission-instructions.pdf : submission-instructions.md ../charter-template.tex
	pandoc submission-instructions.md -f markdown+link_attributes+fenced_code_blocks -o submission-instructions.pdf --template=../charter-template.tex
